sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shubham8896/react-test ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shubham8896/react-test npm test

after_success:
  - docker build -t shubham8896/multi-client ./client
  - docker build -t shubham8896/multi-nginx ./nginx
  - docker build -t shubham8896/multi-server ./server
  - docker build -t shubham8896/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push stephengrider/multi-client
  - docker push stephengrider/multi-nginx
  - docker push stephengrider/multi-server
  - docker push stephengrider/multi-worker


